### ISSUE TITLE
React + Vite configuration

### ISSUE THREAD

**Issue by arionitas** [eapostol/malicious-node-package-checker#2]
Hey Edward,

Arion here from the edX Bootcamp, missing your spotify recommendations.

I wanted to ask if you could help me configure this set up for use via react + vite project build.

Arion

**Comment by eapostol** [comment]
Hey @arionitas , sure I can help, let me know what your availability is like this week

**Comment by arionitas** [comment]
Awesome! Hope we can go through it after class today if you have some time - Universe sent ya my way! Otherwise, I am free pretty much this whole week - so whatever suits you best!

**Comment by arionitas** [comment]
Thanks for the help!
